import tkinter as tk
from tkinter import *

janela = Tk()
janela.geometry('500x600')
janela.title("Infrequência")

frame_num = Label(janela, font=("Arial", 15), width=20, bg="#3b3b3b", text="N° Chamada")
frame_num.grid(column=0, row=0)
frame_nome = Label(janela, font=("Arial", 15), width=100, bg="#fcc058", text="Nome do Aluno")
frame_nome.grid(column=1, row=0)
frame_h1 = Label(janela, font=("Arial", 15), width=5, text="1°")
frame_h1.grid(column=2, row=0)
frame_h2 = Label(janela, font=("Arial", 15), width=5, text="2°")
frame_h2.grid(column=3, row=0)
frame_h3 = Label(janela, font=("Arial", 15), width=5, text="3°")
frame_h3.grid(column=4, row=0)
frame_h4 = Label(janela, font=("Arial", 15), width=5, text="4°")
frame_h4.grid(column=5, row=0)
frame_h5 = Label(janela, font=("Arial", 15), width=5, text="5°")
frame_h5.grid(column=6, row=0)
frame_h6 = Label(janela, font=("Arial", 15), width=5, text="6°")
frame_h6.grid(column=7, row=0)
frame_h7 = Label(janela, font=("Arial", 15), width=5, text="7°")
frame_h7.grid(column=8, row=0)
frame_h8 = Label(janela, font=("Arial", 15), width=5, text="8°")
frame_h8.grid(column=9, row=0)
frame_h9 = Label(janela, font=("Arial", 15), width=5, text="9°")
frame_h9.grid(column=10, row=0)


# configurando frame_num -------------------------------------------------------------------------


frame_n1 = Label(janela, font=("Arial", 12), width=20, text="01")
frame_n1.grid(column=0, row=1)
frame_n2 = Label(janela, font=("Arial", 12), width=20, text="02")
frame_n2.grid(column=0, row=2)
frame_n3 = Label(janela, font=("Arial", 12), width=20, text="03")
frame_n3.grid(column=0, row=3)
frame_n4 = Label(janela, font=("Arial", 12), width=20, text="04")
frame_n4.grid(column=0, row=4)
frame_n5 = Label(janela, font=("Arial", 12), width=20, text="05")
frame_n5.grid(column=0, row=5)
frame_n6 = Label(janela, font=("Arial", 12), width=20, text="06")
frame_n6.grid(column=0, row=6)
frame_n7 = Label(janela, font=("Arial", 12), width=20, text="07")
frame_n7.grid(column=0, row=7)
frame_n8 = Label(janela, font=("Arial", 12), width=20, text="08")
frame_n8.grid(column=0, row=8)
frame_n9 = Label(janela, font=("Arial", 12), width=20, text="09")
frame_n9.grid(column=0, row=9)
frame_n10 = Label(janela, font=("Arial", 12), width=20, text="10")
frame_n10.grid(column=0, row=10)
frame_n11 = Label(janela, font=("Arial", 12), width=20, text="11")
frame_n11.grid(column=0, row=11)
frame_n12 = Label(janela, font=("Arial", 12), width=20, text="12")
frame_n12.grid(column=0, row=12)
frame_n13 = Label(janela, font=("Arial", 12), width=20, text="13")
frame_n13.grid(column=0, row=13)
frame_n14 = Label(janela, font=("Arial", 12), width=20, text="14")
frame_n14.grid(column=0, row=14)
frame_n15 = Label(janela, font=("Arial", 12), width=20, text="15")
frame_n15.grid(column=0, row=15)
frame_n16 = Label(janela, font=("Arial", 12), width=20, text="16")
frame_n16.grid(column=0, row=16)
frame_n17 = Label(janela, font=("Arial", 12), width=20, text="17")
frame_n17.grid(column=0, row=17)
frame_n18 = Label(janela, font=("Arial", 12), width=20, text="18")
frame_n18.grid(column=0, row=18)
frame_n19 = Label(janela, font=("Arial", 12), width=20, text="19")
frame_n19.grid(column=0, row=19)
frame_n20 = Label(janela, font=("Arial", 12), width=20, text="20")
frame_n20.grid(column=0, row=20)
frame_n21 = Label(janela, font=("Arial", 12), width=20, text="21")
frame_n21.grid(column=0, row=21)
frame_n22 = Label(janela, font=("Arial", 12), width=20, text="22")
frame_n22.grid(column=0, row=22)
frame_n23 = Label(janela, font=("Arial", 12), width=20, text="23")
frame_n23.grid(column=0, row=23)
frame_n24 = Label(janela, font=("Arial", 12), width=20, text="24")
frame_n24.grid(column=0, row=24)
frame_n25 = Label(janela, font=("Arial", 12), width=20, text="25")
frame_n25.grid(column=0, row=25)
frame_n26 = Label(janela, font=("Arial", 12), width=20, text="26")
frame_n26.grid(column=0, row=26)
frame_n27 = Label(janela, font=("Arial", 12), width=20, text="27")
frame_n27.grid(column=0, row=27)
frame_n28 = Label(janela, font=("Arial", 12), width=20, text="28")
frame_n28.grid(column=0, row=28)
frame_n529 = Label(janela, font=("Arial", 12), width=20, text="29")
frame_n529.grid(column=0, row=29)
frame_n30 = Label(janela, font=("Arial", 12), width=20, text="30")
frame_n30.grid(column=0, row=30)
frame_n31 = Label(janela, font=("Arial", 12), width=20, text="31")
frame_n31.grid(column=0, row=31)
frame_n32 = Label(janela, font=("Arial", 12), width=20, text="32")
frame_n32.grid(column=0, row=32)
frame_n33 = Label(janela, font=("Arial", 12), width=20, text="33")
frame_n33.grid(column=0, row=33)
frame_n34 = Label(janela, font=("Arial", 12), width=20, text="34")
frame_n34.grid(column=0, row=34)
frame_n35 = Label(janela, font=("Arial", 12), width=20, text="35")
frame_n35.grid(column=0, row=35)
frame_n36 = Label(janela, font=("Arial", 12), width=20, text="36")
frame_n36.grid(column=0, row=36)
frame_n37 = Label(janela, font=("Arial", 12), width=20, text="37")
frame_n37.grid(column=0, row=37)
frame_n38 = Label(janela, font=("Arial", 12), width=20, text="38")
frame_n38.grid(column=0, row=38)


# configurando frame_nome -------------------------------------------------------------------------


frame_no1 = Label(janela, font=("Arial", 12), width=100, text="Aila Vitória Braga da Silva")
frame_no1.grid(column=1, row=1)
frame_no2 = Label(janela, font=("Arial", 12), width=100, text="Alex Moabe Ribeiro de Sousa")
frame_no2.grid(column=1, row=2)
frame_no3 = Label(janela, font=("Arial", 12), width=100, text="Andressa da Silva Matos")
frame_no3.grid(column=1, row=3)
frame_no4 = Label(janela, font=("Arial", 12), width=100, text="Angelo Gabriel Vieira de Oliveira")
frame_no4.grid(column=1, row=4)
frame_no5 = Label(janela, font=("Arial", 12), width=100, text="Ashley Darwin de Souza Duarte")
frame_no5.grid(column=1, row=5)
frame_no6 = Label(janela, font=("Arial", 12), width=100, text="Bruno Henrique do Nascimento Firmino")
frame_no6.grid(column=1, row=6)
frame_no7 = Label(janela, font=("Arial", 12), width=100, text="Cauã Roberto de Souza")
frame_no7.grid(column=1, row=7)
frame_no8 = Label(janela, font=("Arial", 12), width=100, text="Cayo Madson Cardoso de Vasconcelos")
frame_no8.grid(column=1, row=8)
frame_no9 = Label(janela, font=("Arial", 12), width=100, text="Emanoell Edvan Souza da Silva")
frame_no9.grid(column=1, row=9)
frame_no10 = Label(janela, font=("Arial", 12), width=100, text="Eric do Nascimento Sousa Diniz")
frame_no10.grid(column=1, row=10)
frame_no11 = Label(janela, font=("Arial", 12), width=100, text="Fabíola Xavier Ferreira")
frame_no11.grid(column=1, row=11)
frame_no12 = Label(janela, font=("Arial", 12), width=100, text="Felipe Freitas Vieira")
frame_no12.grid(column=1, row=12)
frame_no13 = Label(janela, font=("Arial", 12), width=100, text="Gabriel Holanda de Freitas")
frame_no13.grid(column=1, row=13)
frame_no14 = Label(janela, font=("Arial", 12), width=100, text="Guilherme Dimitri Monteiro de Brito")
frame_no14.grid(column=1, row=14)
frame_no15 = Label(janela, font=("Arial", 12), width=100, text="Heloiza Duarte Verissimo")
frame_no15.grid(column=1, row=15)
frame_no16 = Label(janela, font=("Arial", 12), width=100, text="Igor Dantas Soares")
frame_no16.grid(column=1, row=16)
frame_no17 = Label(janela, font=("Arial", 12), width=100, text="Israel do Monte Silva")
frame_no17.grid(column=1, row=17)
frame_no18 = Label(janela, font=("Arial", 12), width=100, text="Jemily Aguiar do Nascimento")
frame_no18.grid(column=1, row=18)
frame_no19 = Label(janela, font=("Arial", 12), width=100, text="Jennifer Silva Carvalho")
frame_no19.grid(column=1, row=19)
frame_no20 = Label(janela, font=("Arial", 12), width=100, text="João Victor Soares Serafim")
frame_no20.grid(column=1, row=20)
frame_no21 = Label(janela, font=("Arial", 12), width=100, text="Joinkson Laneo Moraes Nascimento")
frame_no21.grid(column=1, row=21)
frame_no22 = Label(janela, font=("Arial", 12), width=100, text="Josiel Sousa Benvindo")
frame_no22.grid(column=1, row=22)
frame_no23 = Label(janela, font=("Arial", 12), width=100, text="Juliana Ramos Lopes")
frame_no23.grid(column=1, row=23)
frame_no24 = Label(janela, font=("Arial", 12), width=100, text="Lara Evelyn de Sousa Pinto")
frame_no24.grid(column=1, row=24)
frame_no25 = Label(janela, font=("Arial", 12), width=100, text="Levi Martins Galvão")
frame_no25.grid(column=1, row=25)
frame_no26 = Label(janela, font=("Arial", 12), width=100, text="Liana Kelly Melo Silva")
frame_no26.grid(column=1, row=26)
frame_no27 = Label(janela, font=("Arial", 12), width=100, text="Luana Hevillyn Morais da Silva")
frame_no27.grid(column=1, row=27)
frame_no28 = Label(janela, font=("Arial", 12), width=100, text="Lywan Riquelme de Oliveira Maia")
frame_no28.grid(column=1, row=28)
frame_no29 = Label(janela, font=("Arial", 12), width=100, text="Maria Eduarda Castro dos Santos")
frame_no29.grid(column=1, row=29)
frame_no30 = Label(janela, font=("Arial", 12), width=100, text="Pedro Gabriel Costa Barbosa")
frame_no30.grid(column=1, row=30)
frame_no31 = Label(janela, font=("Arial", 12), width=100, text="Pedro Lucas Portela Carlos")
frame_no31.grid(column=1, row=31)
frame_no32 = Label(janela, font=("Arial", 12), width=100, text="Raul Ramos Mendes")
frame_no32.grid(column=1, row=32)
frame_no33 = Label(janela, font=("Arial", 12), width=100, text="Samuel Maciel Paiva Neto")
frame_no33.grid(column=1, row=33)
frame_no34 = Label(janela, font=("Arial", 12), width=100, text="Sarah Vitoria Castro Costa")
frame_no34.grid(column=1, row=34)
frame_no35 = Label(janela, font=("Arial", 12), width=100, text="Victor Eduardo Evangelista da Silva")
frame_no35.grid(column=1, row=35)
frame_no36 = Label(janela, font=("Arial", 12), width=100, text="Victor Gutierrez Nunes Cavalcanti")
frame_no36.grid(column=1, row=36)
frame_no37 = Label(janela, font=("Arial", 12), width=100, text="Victória Ketley de Oliveira do Nascimento")
frame_no37.grid(column=1, row=37)
frame_no38 = Label(janela, font=("Arial", 12), width=100, text="Vinnícius Aráujo Sousa")
frame_no38.grid(column=1, row=38)


# configurando CheckButton -------------------------------------------------------------------------



var1 = tk.IntVar()
var2 = tk.IntVar()
var3 = tk.IntVar()
var4 = tk.IntVar()
var5 = tk.IntVar()
var6 = tk.IntVar()
var7 = tk.IntVar()
var8 = tk.IntVar()
var9 = tk.IntVar()


c1 = tk.Checkbutton(janela, text='', variable=var1, onvalue=1, offvalue=0)
c1.grid(column=2, row=1)
c2 = tk.Checkbutton(janela, text='', variable=var2, onvalue=1, offvalue=0)
c2.grid(column=3, row=1)
c3 = tk.Checkbutton(janela, text='', variable=var3, onvalue=1, offvalue=0)
c3.grid(column=4, row=1)
c4 = tk.Checkbutton(janela, text='', variable=var4, onvalue=1, offvalue=0)
c4.grid(column=5, row=1)
c5 = tk.Checkbutton(janela, text='', variable=var5, onvalue=1, offvalue=0)
c5.grid(column=6, row=1)
c6 = tk.Checkbutton(janela, text='', variable=var6, onvalue=1, offvalue=0)
c6.grid(column=7, row=1)
c7 = tk.Checkbutton(janela, text='', variable=var7, onvalue=1, offvalue=0)
c7.grid(column=8, row=1)
c8 = tk.Checkbutton(janela, text='', variable=var8, onvalue=1, offvalue=0)
c8.grid(column=9, row=1)
c9 = tk.Checkbutton(janela, text='', variable=var9, onvalue=1, offvalue=0)
c9.grid(column=10, row=1)



janela.mainloop()
